public with sharing class ContactEventClone {
    //-----------------------------
    //
    //stub for deleted Apex Class
    // 
    //-----------------------------

    // Class properties
    private Id eventIdOld;
    
    // Default constructor
    public ContactEventClone (){
    // do nothing
    }

    //
    //  TEST ContactEventClone
    //
    private static testMethod void testContactEventClone() {
    ContactEventClone cnt = new ContactEventClone();
    cnt = new ContactEventClone();
    }
}